### ISSUE TITLE
compile error using buildToolsVersion "23.0.1"

### ISSUE THREAD

**Issue by ss780217** [googlesamples/android-BasicRenderScript#1]
logcat
Error:Execution failed for task ':Application:compileDebugRenderscript'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\sdk\build-tools\23.0.1\llvm-rs-cc.exe'' finished with non-zero exit value -1073741515

But using buildToolsVersion "21.1.2" can compile the project successfully.

**Comment by askaralic** [comment]
i too get same problem please help

**Comment by max005** [comment]
I get same error too~

**Comment by shippoo** [comment]
this is my error

compileDebugRenderscript
C:\Users***\AppData\Local\Android\sdk\build-tools\23.0.3\renderscript\clang-include\stdbool.h
Error:(1, 1) error: unknown type name 'b'
Error:(1, 2) error: expected identifier or '('
Error:(1, 7) error: source file is not valid UTF-8
Error:(1, 41) error: source file is not valid UTF-8
Error:(1, 42) error: extraneous closing brace ('}')
.
.
.
Error:Execution failed for task ':M_Gallery2:compileDebugRenderscript'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users***\AppData\Local\Android\sdk\build-tools\23.0.3\llvm-rs-cc.exe'' finished with non-zero exit value 1

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
