### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 48771084 byte allocation with 16766176 free bytes and 33MB until OOM                                                                                      

### ISSUE THREAD

**Issue by krishna0808** [googlesamples/android-BasicRenderScript#2]
To do some Renderscript performance benchmarking, i tried to run the sample on different devices like Nexus 6P & Samsung S7. I changed the default image to a 12 MP image takes from Nexus 6P camera. When i launch app, it crashes with OutOfMemory error. Why are we creating so many Bitmaps & Allocations? How can i make it run?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
