### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by nickgtest** [googlesamples/android-BasicRenderScript#4]
Cant compile "compile files('renderscript-v8.jar')" due to missing the file and you have two defaultConfig that will cause problem in the future In the build.gradle file. Please update the gradle file. Thanks

**Comment by ducrohet** [comment]
`compile files('renderscript-v8.jar')`  is not needed. This file is in the SDK inside the build tools folders, and the Gradle plugin add this to the app classpath automatically.

the other issue is indeed that `defaultConfig` should not be under `android.sourceSets`. Just move its content to `android.defaultConfig`

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
